### ISSUE TITLE
Trying to reading all relationship tuples results in an Exception (dotnet)

### ISSUE THREAD

**Issue by homorozeanu** [openfga/dotnet-sdk#31]
I am trying to migrate existing relationship tuples after updating the model, following the guide here: https://openfga.dev/docs/modeling/migrating/migrating-relations

On [step 3](https://openfga.dev/docs/modeling/migrating/migrating-relations) when trying to read all relationship tuples I get the following exception:

```csharp
OpenFga.Sdk.Exceptions.FgaApiValidationError: the 'tuple_key' field was provided but the object type field is required and both the object id and user cannot be empty
   at OpenFga.Sdk.ApiClient.BaseClient.SendRequestAsync[T](HttpRequestMessage request, IDictionary`2 additionalHeaders, String apiName, CancellationToken cancellationToken)
   at OpenFga.Sdk.ApiClient.BaseClient.SendRequestAsync[T](RequestBuilder requestBuilder, IDictionary`2 additionalHeaders, String apiName, CancellationToken cancellationToken)
   at OpenFga.Sdk.ApiClient.ApiClient.<>c__DisplayClass4_0`1.<<SendRequestAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenFga.Sdk.ApiClient.ApiClient.Retry[TResult](Func`1 retryable)
   at OpenFga.Sdk.ApiClient.ApiClient.Retry[TResult](Func`1 retryable)
   at OpenFga.Sdk.ApiClient.ApiClient.SendRequestAsync[T](RequestBuilder requestBuilder, String apiName, CancellationToken cancellationToken)
   at OpenFga.Sdk.Api.OpenFgaApi.Read(ReadRequest body, CancellationToken cancellationToken)
   at OpenFga.Sdk.Client.OpenFgaClient.Read(ClientReadRequest body, IClientReadOptions options, CancellationToken cancellationToken)
   ...
```

Here is the code I am trying to execute:
```csharp
var options = new ClientReadOptions { };
var body = new ClientReadRequest { };

_openFgaClient.StoreId = storeId;
_openFgaClient.AuthorizationModelId = modelId;
        
var response = await _openFgaClient.Read(body, options);
```

What is the correct way to read all relationship tuples at once with the OpenFGA .NET SDK?

**Comment by homorozeanu** [comment]
Hi @rhamzeh,

we found out that the Java SDK had the same issue and was fixed, here the link: https://github.com/openfga/java-sdk/issues/30

Best regards!
