### ISSUE TITLE
Provide client service through interfaces to improve decoupling and testability of client application

### ISSUE THREAD

**Issue by bubianchi-criteo** [openfga/dotnet-sdk#56]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

I'm prototyping an application that leverages this very useful SDK. To develop our unit tests of my application code, I could not easily simulate and mock  specific behaviors in particular for error cases because the [`OpenFgaClient`](https://github.com/openfga/dotnet-sdk/blob/main/src/OpenFga.Sdk/Client/Client.cs) is provided as a class without overridable methods.

### Describe the ideal solution

We could improve the SDK extensibility and client application testability by providing features through interfaces, in particular a `IOpenFgaClient` interface with the public methods implemented by [`OpenFgaClient`](https://github.com/openfga/dotnet-sdk/blob/main/src/OpenFga.Sdk/Client/Client.cs). 
Moreover the actual construction of the OpenFga client could be managed through a factory pattern, and with its own interface would enable using natively Dependency Injection from AspNet

**Comment by rhamzeh** [comment]
Thanks for the suggestion @bubianchi-criteo - added to our backlog. Feel free to contribute the change if you are willing!

**Comment by CharlieDigital** [comment]
If I understand correctly, the work would be here: https://github.com/openfga/sdk-generator/tree/main/config/clients/dotnet/template?

**Comment by CharlieDigital** [comment]
Might give it a shot this weekend.  My thought process:

1. Add a new `config/clients/dotnet/template/IOpenFgaClient.mustache`
2. `IOpenFgaClient.mustache` will largely have the same public properties and methods as `config/clients/dotnet/template/Client/Client.mustache` minus the `IDisposable` implementation
3. Update `config/clients/dotnet/template/Client/Client.mustache` to include `IOpenFgaClient` in the class declaration

Does that sound about right?

Sidequest: Update the comments to be idiomatic C# XML comments

**Comment by CharlieDigital** [comment]
@aaguiarz @rhamzeh I'm trying to take this on and running into a lot of issues with the generator project.  I'm following the instructions here:

https://github.com/openfga/sdk-generator?tab=readme-ov-file#getting-started

When I run `make`, I get the following error:

```
[main] INFO  o.o.codegen.TemplateManager - writing file /clients/fga-js-sdk/.openapi-generator/VERSION
Exception in thread "main" java.lang.RuntimeException: Could not generate supporting file '/clients/fga-js-sdk/.openapi-generator/VERSION'
        at org.openapitools.codegen.DefaultGenerator.generateVersionMetadata(DefaultGenerator.java:1468)
        at org.openapitools.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:784)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:928)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.nio.file.NoSuchFileException: /clients/fga-js-sdk/.openapi-generator/VERSION
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
        at java.base/java.nio.file.Files.write(Unknown Source)
        at org.openapitools.codegen.TemplateManager.writeToFileRaw(TemplateManager.java:255)
        at org.openapitools.codegen.TemplateManager.writeToFile(TemplateManager.java:237)
        at org.openapitools.codegen.DefaultGenerator.generateVersionMetadata(DefaultGenerator.java:1460)
        ... 5 more
make[1]: *** [build-client] Error 1
make: *** [build-client-js] Error 2
```

If I try to build just the .NET client. via `make -d build-client-dotnet`:

```
/Users/cchen/code/oss/openfga-sdk-generator
Exception in thread "main" java.lang.RuntimeException: Unknown library: httpclient
Available libraries:
  NONE
        at org.openapitools.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:5943)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:656)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Reaping losing child 0x124e095c0 PID 57528 
make[1]: *** [build-client] Error 1
Removing child 0x124e095c0 PID 57528 from chain.
Reaping losing child 0x11e904ee0 PID 57452 
make: *** [build-client-dotnet] Error 2
Removing child 0x11e904ee0 PID 57452 from chain.
```

Are additional setup instructions I'm missing for the SDK generator?
